# What image are we pulling? What version do we want?
# FROM <YOUR CODE HERE>
FROM mysql/mysql-server

COPY initdb.sql /docker-entrypoint-initdb.d/

# What is the default MySQL port?
# EXPOSE <YOUR CODE HERE>
EXPOSE 80
